# Generated by Django 4.2 on 2024-04-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created',
        ),
    ]
